version: "3.3"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=patitos_db
      - MYSQL_USER=PatitoDB
      - MYSQL_PASSWORD=Clinic@PatitoDB1
      - MYSQL_ROOT_PASSWORD=Minimoocho3Mungui@

    